### ISSUE TITLE
[feat] New methods for CXX bindings

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#12]
- [x] Hide title bar before run
 - [x] Open dev tools
 - [x] Close window
 - [x] On window move
 - [x] On window close
 - [x] On window resize
 - [ ] ~~On window full screen~~
 - [ ] ~~On window maximize~~
 - [ ] ~~On window minimize~~
 - [ ] ~~On window unmaximize~~
 - [ ] ~~On window not responding~~
 - [x] Enable/disable always-on-top windows
 - [x] Support for IPC communication from renderer and C++
 - [x] Support for dynamically creating and destroying windows programmatically
 - [x] Support for setting the window URL dynamically

**Comment by sudo-carson** [comment]
### Notes
- On maximize/minimize is not an event (will be added soon, unless there's a platform-related issue why it wasn't implemented in Tauri)
  * As a temporary workaround, listen for `Resized` and use `is_maximized()`
  * Looks like there's no `is_minimized()` yet, will also be adding that
- Unresponsive window not supported on all platforms, and therefore is not a built-in event
  * As a workaround you can send pings from the window every ~200ms; if Rust misses a few pings, mark it as unresponsive. This is the approach I'm using in [Allie](https://github.com/allie-project).
- Hidden titlebars (while keeping decorations) are a Windows-only feature, and the function will only be available on Windows.
  * GTK+ doesn't allow the removal of the titlebar without also removing decorations.
  * I believe macOS does allow this, and there is a function for it in Millennium Core, but I am unable to test it in my slow macOS VM.

**Comment by sudo-carson** [comment]
Going to wait to push until all APIs are complete, but the APIs listed in this issue are currently complete. Will push before v1.0.0-beta.3
