### ISSUE TITLE
[feat] Java bindings support

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#14]
Oh and btw, um gradle is 900 times easier than .cmake

**Comment by sudo-carson** [comment]
Until official bindings release, you can use the C bindings with JNI.

**Comment by XFaonAE** [comment]
![153421492-7b1c2a79-74e6-40bf-8141-c92d28b7012d](https://user-images.githubusercontent.com/85759101/166113607-386cc54d-2d46-4130-9b00-7d439c45e89f.png)

**Comment by sudo-carson** [comment]
I attempted to get some basic bindings working but ran into problems with Gradle + Cargo. I will accept a PR for this, but for now, I will close this and revisit it later on when the project and API are more stable.
