### ISSUE TITLE
Window snap layouts support

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#18]
I found a solution, need more info?

**Comment by XFaonAE** [comment]
By snap im talkin about dis
![image](https://user-images.githubusercontent.com/85759101/169431764-a0c3490b-a362-4f71-80c7-8c497d08007f.png)
I got it working well in java

**Comment by XFaonAE** [comment]
![image](https://user-images.githubusercontent.com/85759101/169445695-6449e631-4a6d-4987-98b5-b166cf6c9e08.png)
Alright snap layout working super epok

**Comment by sudo-carson** [comment]
Please PM me on Discord with more info @XFaonAE

**Comment by sudo-carson** [comment]
Unfortunately WebView2 does not allow for overriding NCHITTEST within the webview 🥲
