### ISSUE TITLE
Vulkan API support

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#19]
![image](https://user-images.githubusercontent.com/85759101/171011006-fac43af9-5d3c-4376-921f-9cb0260f30e0.png)
Make it so we can 
 - Run C++ in millennium
 - Load vulkan via a GL viewport in HTML

**Comment by sudo-carson** [comment]
Sorry, I don't understand your requests.

You can run C++ in Millennium via something like [Emscripten](https://emscripten.org/). You can interact with Millennium in C++ via the C++ bindings.

[WebGPU](https://www.w3.org/TR/webgpu/) exports a Vulkan-like API and I believe it should be enabled for WebView2. Alternatively, there's [wgpu](https://wgpu.rs/), which implements a WebGL 2 backend under the WebGPU API.

**Comment by XFaonAE** [comment]
Well could u ship ems with mill?

**Comment by sudo-carson** [comment]
No. Millennium is a Rust project, and I want to keep the size (including development tools) as small as possible. It's not practical to ship something as massive as Emscripten when **very** few users would use it.

Millennium also does not (and will not) take care of compiling frontend code, so you are free to use whatever compiler/bundler/build system you wish. As long as you can get HTML & JavaScript out, Millennium will happily run it.
