### ISSUE TITLE
Hidden titlebar support for Crystal OS

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#21]
On CrystalOS GTK isnt used, and so hidden titlebar would not work correctly, instead a command is used to handle that
First check if the OS is Crystal by checking to see if `OS_CRYSTAL_SKY` exists in the env vars.

Then get the x11 window ID from millennium
and run this command
```
os-crystal-sky --hint-w TitleBar --hint-v false --hint-wid <X11WindowID>
```

**Comment by sudo-carson** [comment]
If GTK isn't used, then a lot more than the hidden titlebar won't work :^)

I highly recommend you provide GTK in your repository for app compatibility (because a lot more apps use GTK besides Millennium). Either that or provide both a GTK-esque window library with a WebKit webview library a la `libwebkit2gtk`. I'd accept a PR for it, though I'm not too keen on having 2 separate backends for Linux.

**Comment by XFaonAE** [comment]
You dont need to support a new backend, GTK is supported, but its better to use the command as thats the primary way of doing it in Crystal. Plus GTK is massive, 140mb. THe command tells X server to stop rendering a titlebar

**Comment by sudo-carson** [comment]
> You dont need to support a new backend, GTK is supported, but its better to use the command as thats the primary way of doing it in Crystal. Plus GTK is massive, 140mb. THe command tells X server to stop rendering a titlebar

Thanks for clarifying. I would rather not have to do this through a process, is there a C API I can use instead?

**Comment by XFaonAE** [comment]
Yes
```cxx
#include <OSCrystalSky.h>

OS::SetTitleBarState(winID, false);
```

**Comment by XFaonAE** [comment]
And to check the OS, `OS_CRYSTAL_SKY` would be defined

**Comment by sudo-carson** [comment]
I need a **C** API to be able to interface with it in Rust.

**Comment by XFaonAE** [comment]
Alr the API is now C based, just remove OS::

**Comment by sudo-carson** [comment]
I don't think that's a good idea namespace wise but that's not the point of this issue so whatever 😃

Cool, I'll add this feature as soon as I get an installation of Crystal OS I can test with.

**Comment by sudo-carson** [comment]
I've marked this issue as stale and will close it in 2 weeks if it stays inactive. I need something tangible to test with and it seems [Crystal](https://github.com/SkylixGH/Crystal) development is inactive, at least publicly.

**Comment by XFaonAE** [comment]
Publicly inactive, currently I did end up reworking the CApi but it might not be final in this form
```c
#ifdef __crystal__
#include <crystal.h>
#endif

// ... x window (if using GTK, get the X window pointer)
cxApplyWindowStyle(xWindow, CXWindowStyle.HIDDEN_TITLEBAR, true);

**Comment by sudo-carson** [comment]
Nice. Issue will still be stale until I can get a working OS image though.

**Comment by XFaonAE** [comment]
ok 👍🏼
