### ISSUE TITLE
Need help with Allie voice assistant device

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#22]
Im just gathering parts for the voice assistant, i decided I wont use a rasberie pie, but instead create the computer myself, 
is it ok that Im using a microprocessor instead of a microcontroller, since the microcontroller was a bit limited and I couldnt really chose the amount of ram that i wanted and it was a bit costly, the kicroprocessor was a bit cheaper and so was the memory, cache etc...

**Comment by XFaonAE** [comment]
also I didnt want to be stupid and buy a whole CPU for that, cause well thats way to complex for me, the micrprocessor seems much easier to work with and ive gotten a 16 bit computer working with one before, which ALMOST reached 1ghz

**Comment by sudo-carson** [comment]
**Millennium is unrelated to Allie Project**. Please only open an issue here if you want to report a bug or have a feature request **for Millennium**. Use [Discussions](https://github.com/pykeio/millennium/discussions) or the [Discord server](https://discord.com/invite/CETPevXFgD) for everything else, including questions **pertaining to Millennium**.

Besides, Allie works best on 64-bit ARMv8 CPUs with at least 3 GB of memory. There is no support for 16- or 32-bit processors.
