### ISSUE TITLE
link to docs?

### ISSUE THREAD

**Issue by wez** [pykeio/millennium#23]
The readme points to https://millennium.pyke.io/ which doesn't seem like it is related to millennium itself.
It seems like https://github.com/pykeio/millennium/blob/main/docs/docs/main/intro.md should be served somewhere?

**Comment by sudo-carson** [comment]
Sorry about that, the docs website is back up, though it is somewhat barren right now. I'm working on expanding the docs and adding more examples. Feel free to ask any questions in [Discussions](https://github.com/pykeio/millennium/discussions).
