### ISSUE TITLE
[feat] [ ...Multiple ]

### ISSUE THREAD

**Issue by XFaonAE** [pykeio/millennium#3]
- [ ] Display capture (without browser popup)
 - [x] Always on top window
 - [ ] ~~JS event listeners for titlebar~~
 - [x] Hide titlebar support

**Comment by XFaonAE** [comment]
*just relised i came off a bit demanding, sorry bout that*

**Comment by sudo-carson** [comment]
Display capture is going to be particularly tricky, most likely I will implement my own display/window capturer in Rust, which you'll be able to interface with via Node bindings. Frontend support will be significantly harder as I don't have low-level access to WebRTC, but the IPC system *should* be fast enough to handle 1080p60 + 48KHz audio if you really need to do it on the frontend...

Hidden titlebars (while keeping window decorations) were implemented in Millennium Core for Windows in [`0964cb3`](https://github.com/pykeio/millennium/commit/0964cb3a0f24119708094cf4ce5a917e2dc1e6d1). I'll have to implement this on Linux, but the macOS implementation is there but not currently enabled, I'll have to do some more testing with it when I get some recent Mac hardware.

<span>#</span>3 is not clear to me. could you explain that a bit more?

Always-on-top windows were implemented in Tauri long ago and supported in Millennium 🙂

**Comment by sudo-carson** [comment]
@XFaonAE would you be ok with an FFmpeg-based display/window capturer that can stream via RTMP? FFmpeg would be the fastest solution and already supports RTMP streaming (which you would most likely use for video streaming anyways), plus it's already cross platform and way more maintained than Millennium probably ever will be 😅

**Comment by XFaonAE** [comment]
👍

**Comment by sudo-carson** [comment]
Display/window capture will be moved to hfm, as I feel it's too niche to warrant adding that bloat to Millennium. https://github.com/pykeio/hfm
